#
# Copyright © 2013-2020, The SeedStack authors <http://seedstack.org>
#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#

version: '3'
services:
  db:
    image: "postgres:13-alpine"
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
  api:
    image: "seedstack/i18n-service:latest"
    links:
      - db
    ports:
      - 8080:8080
    environment:
      DB_URL: jdbc:postgresql://db:5432/${DB_NAME}?user=${DB_USER}&password=${DB_PASSWORD}
      OAUTH_DISCOVERY_DOC: ${OAUTH_DISCOVERY_DOC}
      OAUTH_AUDIENCE: ${OAUTH_AUDIENCE}
