#
# Copyright © 2013-2020, The SeedStack authors <http://seedstack.org>
#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#

application:
  id: seedstack-i18n-service
  name: SeedStack i18n service

logging:
  level: DEBUG

jdbc:
  datasources:
    ds:
      provider: org.seedstack.jdbc.internal.datasource.HikariDataSourceProvider
      url: ${env.DB_URL}

jpa:
  units:
    seed-i18n-domain:
      datasource: ds
      properties:
        hibernate.dialect: org.hibernate.dialect.PostgreSQL10Dialect
        hibernate.hbm2ddl.auto: update

security:
  realms: OAuthRealm
  web:
    urls:
      - pattern: /**
        filters: oauth
  oauth:
    discoveryDocument: ${env.OAUTH_DISCOVERY_DOC}
    allowedAudiences: ${env.OAUTH_AUDIENCE}
    treatScopesAsPermissions: true

